"""initial tables

Revision ID: 14c51c9b2e02
Revises: 
Create Date: 2026-03-09 15:13:51.680761
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '14c51c9b2e02'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('export_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requested_by', sa.String(length=200), nullable=False),
    sa.Column('export_format', sa.Enum('json', 'csv', 'xlsx', name='exportformat'), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='exportstatus'), nullable=False),
    sa.Column('s3_key', sa.Text(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jurisdiction_code', sa.String(length=20), nullable=False),
    sa.Column('jurisdiction_name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('connector_id', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_jurisdiction_code'), 'sources', ['jurisdiction_code'], unique=False)
    op.create_table('document_families',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('canonical_title', sa.Text(), nullable=False),
    sa.Column('short_cite', sa.String(length=200), nullable=True),
    sa.Column('subject_area', sa.String(length=200), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_families_source_id'), 'document_families', ['source_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(length=100), nullable=False),
    sa.Column('predecessor_id', sa.Integer(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('sunset_date', sa.Date(), nullable=True),
    sa.Column('temporal_status', sa.Enum('enacted', 'active', 'future_effective', 'repealed', 'stayed', name='temporalstatus'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['document_families.id'], ),
    sa.ForeignKeyConstraint(['predecessor_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_versions_family_id'), 'document_versions', ['family_id'], unique=False)
    op.create_table('extraction_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_version_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_total', sa.Integer(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_jobs_document_version_id'), 'extraction_jobs', ['document_version_id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_version_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'fetching', 'fetched', 'parsing', 'parsed', 'normalizing', 'completed', 'failed', name='ingestionstatus'), nullable=False),
    sa.Column('fetch_url', sa.Text(), nullable=True),
    sa.Column('fetch_started_at', sa.DateTime(), nullable=True),
    sa.Column('fetch_completed_at', sa.DateTime(), nullable=True),
    sa.Column('parse_started_at', sa.DateTime(), nullable=True),
    sa.Column('parse_completed_at', sa.DateTime(), nullable=True),
    sa.Column('parse_quality_score', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_document_version_id'), 'ingestion_jobs', ['document_version_id'], unique=False)
    op.create_table('legal_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_version_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('enactment', 'amendment', 'repeal', 'stay', 'effective', 'sunset', name='legaleventtype'), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('authority', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_events_document_version_id'), 'legal_events', ['document_version_id'], unique=False)
    op.create_index('ix_legal_events_version_date', 'legal_events', ['document_version_id', 'event_date'], unique=False)
    op.create_table('normalized_source_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_version_id', sa.Integer(), nullable=False),
    sa.Column('section_path', sa.Text(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('char_offset_start', sa.Integer(), nullable=True),
    sa.Column('char_offset_end', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_source_records_document_version_id'), 'normalized_source_records', ['document_version_id'], unique=False)
    op.create_index('ix_nsr_version_ordinal', 'normalized_source_records', ['document_version_id', 'ordinal'], unique=False)
    op.create_table('raw_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_version_id', sa.Integer(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('s3_key', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256_hash')
    )
    op.create_index(op.f('ix_raw_artifacts_document_version_id'), 'raw_artifacts', ['document_version_id'], unique=False)
    op.create_table('extractions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_record_id', sa.Integer(), nullable=False),
    sa.Column('extraction_type', sa.Enum('obligation', 'definition', 'actor_mapping', 'threshold', 'exception', 'enforcement', 'timeline', 'framework_ref', 'ambiguity', name='extractiontype'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_spans', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_tier', sa.Enum('A', 'B', 'C', 'D', name='confidencetier'), nullable=False),
    sa.Column('review_status', sa.Enum('pending', 'approved', 'rejected', 'needs_revision', name='reviewstatus'), nullable=False),
    sa.Column('prompt_template_version', sa.String(length=40), nullable=True),
    sa.Column('model_id', sa.String(length=100), nullable=True),
    sa.Column('extraction_job_id', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['extraction_job_id'], ['extraction_jobs.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['normalized_source_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extractions_extraction_job_id'), 'extractions', ['extraction_job_id'], unique=False)
    op.create_index(op.f('ix_extractions_extraction_type'), 'extractions', ['extraction_type'], unique=False)
    op.create_index('ix_extractions_payload', 'extractions', ['payload'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_extractions_source_record_id'), 'extractions', ['source_record_id'], unique=False)
    op.create_index('ix_extractions_type_status', 'extractions', ['extraction_type', 'review_status'], unique=False)
    op.create_table('applicability_conditions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('node_type', sa.Enum('AND', 'OR', 'NOT', 'LEAF', name='conditionnodetype'), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('condition_text', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['applicability_conditions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicability_conditions_extraction_id'), 'applicability_conditions', ['extraction_id'], unique=False)
    op.create_table('obligation_dependencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_extraction_id', sa.Integer(), nullable=False),
    sa.Column('child_extraction_id', sa.Integer(), nullable=False),
    sa.Column('dependency_type', sa.Enum('requires_definition', 'modifies', 'excepts', 'enforces', 'references', 'supersedes', name='dependencytype'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['child_extraction_id'], ['extractions.id'], ),
    sa.ForeignKeyConstraint(['parent_extraction_id'], ['extractions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_extraction_id', 'child_extraction_id', 'dependency_type', name='uq_obligation_dep')
    )
    op.create_index(op.f('ix_obligation_dependencies_child_extraction_id'), 'obligation_dependencies', ['child_extraction_id'], unique=False)
    op.create_index(op.f('ix_obligation_dependencies_parent_extraction_id'), 'obligation_dependencies', ['parent_extraction_id'], unique=False)
    op.create_table('review_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'needs_revision', name='reviewstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extraction_id')
    )
    op.create_table('review_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('queue_item_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('pending', 'approved', 'rejected', 'needs_revision', name='reviewstatus'), nullable=False),
    sa.Column('reviewer', sa.String(length=200), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('corrections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['queue_item_id'], ['review_queue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_actions_queue_item_id'), 'review_actions', ['queue_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_actions_queue_item_id'), table_name='review_actions')
    op.drop_table('review_actions')
    op.drop_table('review_queue')
    op.drop_index(op.f('ix_obligation_dependencies_parent_extraction_id'), table_name='obligation_dependencies')
    op.drop_index(op.f('ix_obligation_dependencies_child_extraction_id'), table_name='obligation_dependencies')
    op.drop_table('obligation_dependencies')
    op.drop_index(op.f('ix_applicability_conditions_extraction_id'), table_name='applicability_conditions')
    op.drop_table('applicability_conditions')
    op.drop_index('ix_extractions_type_status', table_name='extractions')
    op.drop_index(op.f('ix_extractions_source_record_id'), table_name='extractions')
    op.drop_index('ix_extractions_payload', table_name='extractions', postgresql_using='gin')
    op.drop_index(op.f('ix_extractions_extraction_type'), table_name='extractions')
    op.drop_index(op.f('ix_extractions_extraction_job_id'), table_name='extractions')
    op.drop_table('extractions')
    op.drop_index(op.f('ix_raw_artifacts_document_version_id'), table_name='raw_artifacts')
    op.drop_table('raw_artifacts')
    op.drop_index('ix_nsr_version_ordinal', table_name='normalized_source_records')
    op.drop_index(op.f('ix_normalized_source_records_document_version_id'), table_name='normalized_source_records')
    op.drop_table('normalized_source_records')
    op.drop_index('ix_legal_events_version_date', table_name='legal_events')
    op.drop_index(op.f('ix_legal_events_document_version_id'), table_name='legal_events')
    op.drop_table('legal_events')
    op.drop_index(op.f('ix_ingestion_jobs_document_version_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_extraction_jobs_document_version_id'), table_name='extraction_jobs')
    op.drop_table('extraction_jobs')
    op.drop_index(op.f('ix_document_versions_family_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_document_families_source_id'), table_name='document_families')
    op.drop_table('document_families')
    op.drop_index(op.f('ix_sources_jurisdiction_code'), table_name='sources')
    op.drop_table('sources')
    op.drop_table('export_jobs')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
